sudo: required

services:
  - docker

before_install:
  - docker build -t unidata/tomcat-docker:latest .
  - wget -O `pwd`/.travis/sample.war https://tomcat.apache.org/tomcat-8.0-doc/appdev/sample/sample.war
  - docker run --name tomcat -v `pwd`/.travis:/travis -v `pwd`/.travis:/usr/local/tomcat/webapps -d -p 8080:8080 unidata/tomcat-docker:latest
  - curl -o /dev/null http://127.0.0.1:8080/sample/index.html || true
  # Give chance for Tomcat to fire up
  - sleep 300

script:
  - ./.travis/test.sh
